const PRIMARY_COLOR = '#FFA500';
const SECONDARY_COLOR = '#FFD700';
const ACCENT_COLOR = '#FF6347';
const DARK_COLOR = '#000000';
const DARK_PAGE_COLOR = '#1d1d1d';
const LIGHT_COLOR = '#e0e0e0';
const POSITIVE_COLOR = '#25d366';
const NEGATIVE_COLOR = '#f54336';
const INFO_COLOR = '#31ccec';
const WARNING_COLOR = '#ffe680';

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  ACCENT_COLOR,
  DARK_COLOR,
  DARK_PAGE_COLOR,
  LIGHT_COLOR,
  POSITIVE_COLOR,
  NEGATIVE_COLOR,
  INFO_COLOR,
  WARNING_COLOR,
};
